stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA


build:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker info
  script:
    - docker build -t $DOCKER_IMAGE_TAG .
    - docker push $DOCKER_IMAGE_TAG
  only:
    - master

deploy:
  stage: deploy
  variables:
    DEPLOY_SUFFIX: prod
    DEPLOY_HOST: todo.chrupek.tech
  environment:
    name: production
    url: http://todo.chrupek.tech
  image: roffe/kubectl:v1.13.2
  script:
   - kubectl delete --ignore-not-found=true secret gitlab-auth
   - kubectl create secret docker-registry gitlab-auth --docker-server=$CI_REGISTRY --docker-username=$KUBE_PULL_USER --docker-password=$KUBE_PULL_PASS
   - cat deployment.yaml | envsubst | kubectl apply -f -
  only:
    - master

review:
  stage: deploy
  variables:
    DEPLOY_SUFFIX: $CI_COMMIT_REF_SLUG
    DEPLOY_HOST: todo-$CI_COMMIT_REF_SLUG.chrupek.tech
  environment:
    name: production
    url: http://todo-$CI_COMMIT_REF_SLUG.chrupek.tech
    on_stop: stop_review
  image: roffe/kubectl:v1.13.2
  script:
  - echo $KUBE_PULL_USER;
  #  - kubectl delete --ignore-not-found=true secret gitlab-auth
  #  - kubectl create secret docker-registry gitlab-auth --docker-server=$CI_REGISTRY --docker-username=$KUBE_PULL_USER --docker-password=$KUBE_PULL_PASS
  #  - cat deployment.yaml | envsubst | kubectl apply -f -
  except:
    - master

stop_review:
  stage: deploy
  variables:
    GIT_STRATEGY: none
    DEPLOY_SUFFIX: $CI_COMMIT_REF_SLUG
    DEPLOY_HOST: todo-$CI_COMMIT_REF_SLUG.chrupek.tech
  environment:
    name: review/$CI_COMMIT_REF_SLUG
    action: stop
  image: roffe/kubectl:v1.13.2
  script:
    - kubectl delete service/go-todo-frontend-$DEPLOY_SUFFIX
    - kubectl delete deploy/go-todo-frontend-$DEPLOY_SUFFIX
    - kubectl delete ingress/go-todo-ingress-$DEPLOY_SUFFIX
  when: manual
  except:
    - master