apiVersion: v1
kind: Service
metadata:
  name: go-todo-front-svc
spec:
  selector:
    app: go-todo-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-todo-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-todo-frontend
  template:
    metadata:
      labels:
        app: go-todo-frontend
    spec:
      containers:
      - name: go-todo-frontend
        image: "${DOCKER_IMAGE_TAG}"
        resources:
          limits:
            memory: "128Mi"
            cpu: "0.2"
        ports:
        - containerPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-todo-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: todo.chrupek.tech
    http:
      paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: go-todo-front-svc
              port: 
                number: 80
